version: "3.7"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
      POSTGRES_MULTIPLE_DATABASES: keycloak,backend
    volumes:
      - postgres-db:/data/postgres
      - ./multi_db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - bank-network
  # pgadmin on localhost:5433
  # connect to db:5432
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5433:80"
    networks:
      - bank-network
    depends_on:
      - db
  proto:
    build: ./
    ports:
      - "8080:8080"
    networks:
      - bank-network
    depends_on:
      - db
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"


volumes:
  postgres-db: {}
  pgadmin-data: {}
networks:
  bank-network:
    driver: bridge